# Generated by Django 5.1.1 on 2024-11-06 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=65, verbose_name='Nome')),
                ('especialidade', models.CharField(max_length=65, verbose_name='Especialidade')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.FloatField()),
                ('descricao', models.TextField()),
                ('duracao_estimativa', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(choices=[('ESPECIE', 'Espécie'), ('PIX', 'PIX'), ('CREDITO', 'Crédito')], default='ESPECIE', max_length=7, verbose_name='Forma de pagamento')),
                ('status', models.CharField(choices=[('P', 'PENDENTE'), ('A', 'EM ANDAMENTO'), ('F', 'FINALIZADO')], default='P', max_length=1, verbose_name='Status')),
                ('data_hora', models.DateTimeField()),
                ('registro', models.DateTimeField(auto_now_add=True)),
                ('horario_agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.horario', verbose_name='Horarios Disponiveis')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.medico', verbose_name='Médico')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.servico')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
        migrations.CreateModel(
            name='ServicosAgendamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('id_agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.agendamento')),
                ('id_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.servico')),
            ],
        ),
    ]
