# Generated by Django 5.1.1 on 2024-11-13 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=65, verbose_name='Nome')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=65, verbose_name='Nome')),
                ('especialidade', models.CharField(max_length=65, verbose_name='Especialidade')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.FloatField()),
                ('descricao', models.TextField()),
                ('duracao_estimativa', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='ServicosAgendamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('horario', models.CharField(choices=[('08:00 - 09:00', '08:00 - 09:00'), ('09:00 - 10:00', '09:00 - 10:00'), ('10:00 - 11:00', '10:00 - 11:00'), ('11:00 - 12:00', '11:00 - 12:00'), ('12:00 - 13:00', '12:00 - 13:00')], default='1', max_length=13, verbose_name='Horário')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.medico', verbose_name='Médico')),
                ('id_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.servico', verbose_name='Serviço')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=65, verbose_name='Nome')),
                ('cpf_cliente', models.CharField(max_length=11, verbose_name='CPF')),
                ('forma_pagamento', models.CharField(choices=[('ESPECIE', 'Espécie'), ('PIX', 'PIX'), ('CREDITO', 'Crédito')], default='ESPECIE', max_length=7, verbose_name='Forma de pagamento')),
                ('status', models.CharField(choices=[('P', 'PENDENTE'), ('A', 'EM ANDAMENTO'), ('F', 'FINALIZADO')], default='P', max_length=1, verbose_name='Status')),
                ('data', models.DateField(verbose_name='Data')),
                ('registro', models.DateTimeField(auto_now_add=True)),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.medico', verbose_name='Médico')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.servicosagendamentos', verbose_name='Serviço, Médico e Horário disponiveis')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
    ]
